Feature sum
cosorio94/X-Cell pull request #3
Opened 2017-05-05 00:30 UTC by cosorio94

Made fixes from PR review.

2017-05-05 01:52 UTC, speschellk commented
Please go through your files and replace all "var" identifiers with either "let" or "const". Since let and const were introduced with ES6 in early 2016, we don't have to use var anymore.

2017-05-05 01:52 UTC, speschellk requested changes

2017-05-05 01:52 UTC, speschellk commented on client/js/test/fixtures/sheet-container.html
> +      <tr>
Now the alignment is good, but <tfoot> needs to be below <tbody> in a table.

2017-05-06 00:06 UTC, cosorio94 commented on client/js/test/fixtures/sheet-container.html
> +      <tr>
Hi Kay. I am not quite sure I understand what you mean here. I checked the sheet-container.html file and the thead, tfoot, and tbody tags are all below the table tag. Please help me clarify what I should change. Thanks!

2017-05-06 00:25 UTC, merged